### ISSUE TITLE
certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials gandi.ini

### ISSUE THREAD

**Issue by kdekooter** [obynio/certbot-plugin-gandi#18] opened 2020-03-31 06:58 UTC
Installed the gandi plugin and tried to run the following command:

`sudo certbot certonly -a certbot-plugin-gandi:dns --certbot-plugin-gandi:dns-credentials gandi.ini -d XXXXX.nl -d \*.XXXXX.nl --server https://acme-v02.api.letsencrypt.org/directory`

Certbot returns the following error: 
`certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials gandi.ini`

Using the latest certbot, version 0.31.0.

Am I missing something here?

**Comment by svalo** [comment] 2020-03-31 16:21
I think its a duplicate of #16

**Comment by kdekooter** [comment] 2020-03-31 18:20
Could well be if I were able to decipher the actual solution from that issue :-).

Maybe the documentation should be updated accordingly?

**Comment by obynio** [comment] 2020-05-17 20:15
The documentation has been updated accordingly

**Closed as completed by obynio** 2020-05-17 20:15 UTC

**Comment by GiantFrog** [comment] 2020-07-15 15:50
Hey, I'm having this same issue, only unlike #16 I am not trying to do anything with cli.ini and am just trying to get this working in the command line. It sounds like you were also just trying to get it working the same way I am, @kdekooter, so did you ever succeed? What was the issue?

**Comment by Protinon** [comment] 2020-07-18 04:08
I also had the same error, not entirely sure how I solved it but I figured out my issue. Running `sudo certbot renew -a certbot-plugin-gandi:dns --server https://acme-v02.api.letsencrypt.org/directory` showed that certbot didn't recognize the Gandi plugin. Re-installing Certbot, the Gandi plugin, and trying again the next day got my renewal to succeed.

**Comment by dimzeta** [comment] 2020-08-23 17:08
> Hey, I'm having this same issue, only unlike #16 I am not trying to do anything with cli.ini and am just trying to get this working in the command line. It sounds like you were also just trying to get it working the same way I am, @kdekooter, so did you ever succeed? What was the issue?

I had the same issue as you. My mistake was I installed the plugin without sudo. I don't know if it's sensitive, but once I did `sudo pip3 install certbot-plugin-gandi` the error disappeared and my certificate has been successfully generated.

**Comment by GiantFrog** [comment] 2020-09-01 20:31
@dimitribocquet That's all it took! Haha, thanks so much. What an easy fix.
